# Generated by Django 4.2.2 on 2023-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('release_date', models.DateField(verbose_name='Fecha de estreno')),
                ('genre', models.CharField(blank=True, choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DOC', 'Documental'), ('SCI', 'Ciencia Ficción'), ('HORR', 'Horror'), ('ANIM', 'Animada')], max_length=5, verbose_name='Género')),
                ('rating', models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Calificación')),
            ],
        ),
    ]
