# Generated by Django 4.2.2 on 2023-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DOC', 'Documental'), ('SCI', 'Ciencia Ficción'), ('HORR', 'Horror'), ('ANIM', 'Animada'), ('DRAM', 'Drama')], max_length=5, verbose_name='Género'),
        ),
    ]
